import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Interview App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon_aq.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Header />
      <body>
        {children}
      </body>
    </html>
  );
}
